=== alvisf/hexclan/src/main/webapp/invoice.dtd
<!ELEMENT invoice (customername,invno,invdate,items,gst,net)>
<!ELEMENT customername (#PCDATA)>
<!ELEMENT invno (#PCDATA)>
<!ELEMENT invdate (#PCDATA)>
<!ELEMENT items (item+)>
<!ELEMENT item (itemno,itemname,itemprice,itemquantity,itemamount)>
<!ELEMENT itemno (#PCDATA)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT itemprice (#PCDATA)>
<!ELEMENT itemquantity (#PCDATA)>
<!ELEMENT itemamount (#PCDATA)>
<!ELEMENT gst (#PCDATA)>
<!ELEMENT net (#PCDATA)>

=== alvisf/hexclan/src/main/webapp/invoice.xml
<!DOCTYPE invoice SYSTEM "C:\Users\ezhil\Documents\workspace-spring-tool-suite-4-4.10.0.RELEASE\springwebproject2\src\main\webapp\invoice.dtd"><invoice><customername>arun</customername><invno>49</invno><invdate>2021-04-21</invdate><items><item><itemno>5</itemno><itemname>dsfsd</itemname><itemprice>300.0</itemprice><itemquantity>1</itemquantity><itemamount>300.0</itemamount></item><item><itemno>23</itemno><itemname>das</itemname><itemprice>111.0</itemprice><itemquantity>2</itemquantity><itemamount>222.0</itemamount></item></items><gst></gst><net>522.0</net></invoice>
